Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\DELL\PycharmProjects\DjangoProject\.venv\Lib\site-packages\django\conf\global_settings.py changed, reloading.
C:\Users\DELL\PycharmProjects\DjangoProject\.venv\Lib\site-packages\django\__init__.py changed, reloading.
C:\Users\DELL\PycharmProjects\DjangoProject\.venv\Lib\site-packages\django\shortcuts.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\DELL\PycharmProjects\DjangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\PycharmProjects\DjangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\PycharmProjects\DjangoProject\solvabilite_app\views.py", line 28, in index
    return render(request, 'solvabilite_app/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\PycharmProjects\DjangoProject\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\PycharmProjects\DjangoProject\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\PycharmProjects\DjangoProject\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\PycharmProjects\DjangoProject\.venv\Lib\site-packages\django\template\base.py", line 173, in render
    with context.bind_template(self):
  File "C:\Program Files\Python312\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\DELL\PycharmProjects\DjangoProject\.venv\Lib\site-packages\django\template\context.py", line 251, in bind_template
    processors = template.engine.template_context_processors + self._processors
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\PycharmProjects\DjangoProject\.venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\PycharmProjects\DjangoProject\.venv\Lib\site-packages\django\template\engine.py", line 116, in template_context_processors
    return tuple(import_string(path) for path in context_processors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\PycharmProjects\DjangoProject\.venv\Lib\site-packages\django\template\engine.py", line 116, in <genexpr>
    return tuple(import_string(path) for path in context_processors)
                 ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\PycharmProjects\DjangoProject\.venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\PycharmProjects\DjangoProject\.venv\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1318, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'solvabilite_app.context_processors'
"GET / HTTP/1.1" 500 124399
C:\Users\DELL\PycharmProjects\DjangoProject\DjangoProject\urls.py changed, reloading.
C:\Users\DELL\PycharmProjects\DjangoProject\DjangoProject\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\DELL\PycharmProjects\DjangoProject\DjangoProject\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\DELL\PycharmProjects\DjangoProject\solvabilite_app\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\DELL\PycharmProjects\DjangoProject\solvabilite_app\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\DELL\PycharmProjects\DjangoProject\DjangoProject\settings.py changed, reloading.
